//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar
{
    using System;
    using System.Collections.Generic;
    /// class that passes to tadetable member
    /// 
    /// int id, DateTime time, string prop, DateTime date
    public partial class Task
    {
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public string prop { get; set; }
        public System.DateTime date { get; set; }
    }
}
